use axum::{
    Json, Router,
    http::{StatusCode, header},
    response::{IntoResponse, Response},
    routing::get,
};
use rand::seq::IndexedRandom;
use serde_json::{Value, json};

pub const ANIMALI: &[&str] = &[
    "Aquila",
    "Ape",
    "Asino",
    "Anatra",
    "Alligatore",
    "Anaconda",
    "Aragosta",
    "Anguilla",
    "Antilope",
    "Airone",
    "Albatro",
    "Allocco",
    "Alpaca",
    "Anconella",
    "Andiroba",
    "Balena",
    "Boa",
    "Bisonte",
    "Bufalo",
    "Badger",
    "Bradipo",
    "Basilisco",
    "Barbicante",
    "Biacco",
    "Branzino",
    "Bucefalo",
    "Bombo",
    "Belga",
    "Bluattrice",
    "Cane",
    "Cavallo",
    "Coccodrillo",
    "Corvo",
    "Capra",
    "Camaleonte",
    "Cigno",
    "Canguro",
    "Civetta",
    "Colomba",
    "Cormorano",
    "Cervo",
    "Cinghiale",
    "Cocorita",
    "Carpa",
    "Delfino",
    "Drago",
    "Dorso",
    "Donnola",
    "Dattero",
    "Diatomo",
    "Daino",
    "Dingo",
    "Dolerite",
    "Dalmata",
    "Elefante",
    "Elefantessa",
    "Emu",
    "Entelodonte",
    "Ermellino",
    "Falco",
    "Formica",
    "Farfalla",
    "Foca",
    "Fenicottero",
    "Fagiano",
    "Fringuello",
    "Fregata",
    "Fusello",
    "Fiorellino",
    "Forbicina",
    "Gatto",
    "Giraffa",
    "Gorilla",
    "Gallina",
    "Gallo",
    "Granchio",
    "Gamberetto",
    "Gabbiano",
    "Gazza",
    "Geco",
    "Gufo",
    "Gazzella",
    "Gibbone",
    "Gracchio",
    "Ippopotamo",
    "Ibis",
    "Iguanodon",
    "Ippocampo",
    "Ippocastano",
    "Insetto",
    "Istrice",
    "Idra",
    "Ibice",
    "Iguana",
    "Leone",
    "Lupo",
    "Lepre",
    "Lince",
    "Libellula",
    "Lucertola",
    "Lamento",
    "Lontra",
    "Locusta",
    "Luccio",
    "Levriero",
    "Mucca",
    "Maiale",
    "Mosca",
    "Medusa",
    "Mulo",
    "Marmotta",
    "Melma",
    "Mangusta",
    "Merletto",
    "Merlo",
    "Mignattino",
    "Muflone",
    "Mandrillo",
    "Nocchiero",
    "Nibbio",
    "Narvalo",
    "Nautilo",
    "Nappa",
    "Orso",
    "Oca",
    "Orangotango",
    "Ocelot",
    "Orice",
    "Ostrica",
    "Ombra",
    "Oriolo",
    "Pecora",
    "Pinguino",
    "Pappagallo",
    "Pantera",
    "Pesce",
    "Polpo",
    "Pelicano",
    "Passero",
    "Picchio",
    "Porco",
    "Pipistrello",
    "Piranha",
    "Pesce palla",
    "Pantera nera",
    "Quaglia",
    "Ragno",
    "Rana",
    "Rospo",
    "Ratto",
    "Riccio",
    "Rinoceronte",
    "Rondine",
    "Rospo comune",
    "Reclusa",
    "Squalo",
    "Serpente",
    "Scimmia",
    "Scorpione",
    "Scimpanzé",
    "Struzzo",
    "Struzza",
    "Seppia",
    "Saiga",
    "Salamandra",
    "Scarafaggio",
    "Stambecco",
    "Storno",
    "Succiacapre",
    "Tigre",
    "Tartaruga",
    "Talpa",
    "Tigre bianca",
    "Topo",
    "Tarchiato",
    "Tinca",
    "Tarantola",
    "Tasso",
    "Tuffetto",
    "Tordo",
    "Uccello",
    "Usignolo",
    "Volpe",
    "Vespa",
    "Vipera",
    "Vitello",
    "Visone",
    "Vombato",
    "Vongola",
    "Varrone",
    "Vetta",
    "Zebra",
    "Zanzara",
    "Zibetto",
    "Zafferano",
    "Zatterino",
    "Zigolo",
    "Zool",
    "Zoccola",
];

pub const SANTI: &[&str] = &[
    "Zio",
    "Dio",
    "Gesù Cristo",
    "Maria Vergine",
    "Spirito Santo",
    "Sant'Agostino",
    "Sant'Andrea",
    "Sant'Anna",
    "Sant'Ambrogio",
    "Sant'Atanasio",
    "Sant'Alessio",
    "San Benedetto",
    "San Bartolomeo",
    "San Bernardo",
    "San Bonaventura",
    "San Bonifacio",
    "San Biagio",
    "San Basilio",
    "San Carlo",
    "San Celestino",
    "San Cesario",
    "San Chiara",
    "San Ciriaco",
    "San Colombano",
    "San Cipriano",
    "San Clemente",
    "San Daniele",
    "San Davide",
    "San Demetrio",
    "San Desiderio",
    "San Domenico",
    "San Dino",
    "Sant'Eusebio",
    "Sant'Efrem",
    "Sant'Enrico",
    "Sant'Emidio",
    "San Fabiano",
    "San Faustino",
    "San Felice",
    "San Fausto",
    "San Fabrizio",
    "San Fortunato",
    "San Gennaro",
    "San Giorgio",
    "San Gerardo",
    "San Gerolamo",
    "San Girolamo",
    "San Guido",
    "San Giustino",
    "San Gaetano",
    "Sant'Ireneo",
    "Sant'Isidoro",
    "Sant'Ivo",
    "San Leonardo",
    "San Lorenzo",
    "San Luca",
    "San Luciano",
    "San Luigi",
    "San Ludovico",
    "San Liborio",
    "San Lino",
    "San Marcello",
    "San Marino",
    "San Martino",
    "San Matteo",
    "San Mattia",
    "San Maurizio",
    "San Massimino",
    "San Marcellino",
    "San Marziale",
    "San Niccolò",
    "San Nilo",
    "San Neri",
    "San Nicomede",
    "Sant'Onofrio",
    "Sant'Onorato",
    "Sant'Odone",
    "San Pancrazio",
    "San Pantaleone",
    "San Pasquale",
    "San Patrizio",
    "San Pio X",
    "San Pio V",
    "San Pompeo",
    "San Porfirio",
    "San Remigio",
    "San Riccardo",
    "San Rocco",
    "San Romano",
    "San Romualdo",
    "San Rossore",
    "San Rufino",
    "San Rufo",
    "San Sabino",
    "San Salvatore",
    "San Samuele",
    "San Sansone",
    "San Sebastiano",
    "San Secondo",
    "San Sergio",
    "San Simeone",
    "San Sisto",
    "San Sosio",
    "San Severo",
    "San Severino",
    "San Teodoro",
    "San Teobaldo",
    "San Teodorico",
    "San Teofilo",
    "San Tommaso",
    "San Tarcisio",
    "San Teonesto",
    "San Teresio",
    "San Valdo",
    "San Valentino",
    "San Valerio",
    "San Valerico",
    "San Venerando",
    "San Venanzio",
    "San Vitaliano",
    "San Vitale",
    "San Vittore",
    "San Vittorino",
    "San Vigilio",
    "San Zaccaria",
    "San Zeno",
    "San Zosimo",
    "San Zenone",
];
#[tokio::main]
async fn main() {
    let router: Router = Router::new()
        .route("/santo", get(rand_santo))
        .route("/animale", get(rand_animale))
        .route("/bestemmia", get(bestemmia))
        .route("/", get(main_page));

    let listener = tokio::net::TcpListener::bind("0.0.0.0:3000")
        .await
        .expect("Port not free");
    println!("Running on port 3000");

    axum::serve(listener, router).await.expect("Server Error");
}

fn random<'t>(arr: &'t [&'t str]) -> &'t str {
    let mut rng = rand::rng();

    arr.choose(&mut rng).copied().unwrap()
}

async fn rand_santo() -> Json<Value> {
    json!({ "santo": random(SANTI)}).into()
}

async fn rand_animale() -> Json<Value> {
    json!({ "animale": random(ANIMALI)}).into()
}

async fn bestemmia() -> Json<Value> {
    json!({"bestemmia": format!("{} {}", random(SANTI), random(ANIMALI))}).into()
}

async fn main_page() -> Response {
    let bytes = std::fs::read("index.html")
        .unwrap_or_else(|_| b"<h1>404 - pagina non trovata</h1>".to_vec());
    (
        StatusCode::OK,
        [(header::CONTENT_TYPE, "text/html; charset=utf-8")],
        bytes,
    )
        .into_response()
}
